import { TextureSource } from "pixi.js";
/** The six face textures of one mip level. */
export interface CubemapFaceSources {
    posx: TextureSource;
    negx: TextureSource;
    posy: TextureSource;
    negy: TextureSource;
    posz: TextureSource;
    negz: TextureSource;
}
/**
 * Texture source for a cube map whose mip levels are supplied by the user,
 * one set of six faces per level, rather than generated by the GPU. This is
 * what pre-filtered environment maps for image-based lighting need: each
 * level holds a different roughness, so `generateMipmap` would be wrong.
 *
 * PixiJS v8 has native cube textures (`viewDimension: "cube"`), but its own
 * cube uploader only uploads level 0 of each face. This source declares its
 * own upload method, registered below, which uploads every level of every
 * face and leaves mipmap generation off.
 */
export declare class CubemapResource extends TextureSource<CubemapFaceSources[]> {
    /**
     * Creates a new cubemap resource from the specified mip levels. Level 0 is
     * the largest; every following level halves the size.
     * @param mipmaps The faces for each mip level.
     */
    constructor(mipmaps: CubemapFaceSources[]);
    /** The mip levels, each holding six faces. */
    get mipmaps(): CubemapFaceSources[];
    /** The number of mip levels. */
    get levels(): number;
    /**
     * Value indicating if every face of every level has loaded, i.e. has a
     * resource with a non-zero size. Faces created from images that are still
     * decoding report a 0x0 size until they finish.
     */
    get valid(): boolean;
    private _onFaceResize;
    private _onFaceUpdate;
    destroy(): void;
}
